services:
  todo-app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/postgres
      - POOL_SIZE=5
      - MAX_OVERFLOW=5
      - POOL_TIMEOUT=60
      - POOL_RECYCLE=1800 
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    volumes:
      - todo-app-postgres-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:8000
    depends_on:
      - todo-app

volumes:
  todo-app-postgres-storage: