services:
  todo-app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/postgres
      - POOL_SIZE=20
      - MAX_OVERFLOW=40
      - POOL_TIMEOUT=60
      - POOL_RECYCLE=1800
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  db:
    image: postgres:17
    volumes:
      - todo-app-postgres-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  todo-app-postgres-storage: